apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace-netalertx.yaml
  - PVC-netalertx.yaml
  - PVC-netalertx-data.yaml
  - deployment-netalertx.yaml
  - service-netalertx.yaml
  - ingress-netalertx.yaml