apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - PVCs.yaml
  - secret-jwt.yaml
  - service-onlyoffice.yaml
  - deployment-onlyoffice-doc.yaml 
  - Ingress-onlyoffice.yaml