apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jellystat
  name: jellystat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellystat
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jellystat
    spec:
      containers:
        - image: cyfershepard/jellystat:1.1.7
          name: jellystat
          resources:
            requests:
              cpu: 300m
              memory: 150Mi
            limits: {}
          env:
            - name: POSTGRES_USER 
              valueFrom:
                secretKeyRef:
                  name: jellystat-db-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jellystat-db-credentials
                  key: password
            - name: POSTGRES_IP
              valueFrom:
                configMapKeyRef:
                  name: jellystat-db-info
                  key: DB_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: jellystat-db-info
                  key: DB_PORT
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: jellystat-db-info
                  key: DB_DATABASE
            - name: JWT_SECRET 
              valueFrom:
                secretKeyRef:
                  name: jellystat-jwt
                  key: JWT
            - name: TZ
              value: "Asia/Riyadh"
            - name: MINIMUM_SECONDS_TO_INCLUDE_PLAYBACK
              value: "5"
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /app/backend/backup-data
              name: jellystat-backup
      restartPolicy: Always
      volumes:
        - name: jellystat-backup
          persistentVolumeClaim:
            claimName: jellystat-backup