apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - PV-storageusers-nfs.yaml
  - PVC-storageusers-nfs.yaml
  - secret-onlyoffice-wopi-secret.yaml
  - gitrepo.yaml
  - helmrelease.yaml