apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tracktor-1
spec:
  ingressClassName: cilium
  rules:
  - host: tracktor-1.almothana.xyz
    http:
      paths:
      - backend:
          service:
            name: tracktor-1
            port:
              number: 3000
        path: /
        pathType: Prefix
  tls:
    - hosts:
        - tracktor-1.almothana.xyz
      secretName: almothana-xyz-tls