apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: [FTName]
spec:
  ingressClassName: nginx
  rules:
  - host: [FTName].almothana.xyz
    http:
      paths:
      - backend:
          service:
            name: [FTName]
            port:
              number: <CHANGE>
        path: /
        pathType: ImplementationSpecific
  tls:
    - hosts:
        - [FTName].almothana.xyz
      secretName: almothana-xyz-tls